baseurl = "https://zacniewski.github.io"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Artur Zacniewski"
canonifyurls  = true
paginate = 5


DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Scientific Developer and Educator"
  # logo = "img/avatar-sponge.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
[[Params.bigimg]]
  src = "img/sphere.jpg"
  desc = ""
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Artur Zacniewski"
  # email = "youremail@domain.com"
  facebook = "artur.zacniewski"
  # googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  # gitlab = "username"
  github = "zacniewski"
  twitter = "zacniewski"
  # reddit = "username"
  linkedin = "artur-zacniewski-29436928"
  # xing = "username"
  stackoverflow = "users/2090474/artur"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #keybase = "username"
  googlescholar = "8O4cHKMAAAAJ&amp;hl=en"
  researchgate = "Artur_Zacniewski"
  orcid = "0000-0002-3604-4051"

[[menu.main]]
    url = "teaching/"
    identifier = "teaching"
    name = "teaching"
    weight = 1

[[menu.main]]
    parent = "teaching"
    name = "Wstęp do Data Science"
    url = "teaching/2019-winter-sux/"
    weight = 1

[[menu.main]]
    parent = "teaching"
    name = "Projektowanie serwisów WWW"
    url = "teaching/2019-winter-www/"
    weight = 2

[[menu.main]]
    parent = "teaching"
    name = "Aplikacje mobilne dla systemu Android"
    url = "teaching/2020-summer-android/"
    weight = 3

[[menu.main]]
    parent = "teaching"
    name = "Algorytmy ewolucyjne"
    url = "teaching/2020-summer-ae/"
    weight = 4

[[menu.main]]
    parent = "teaching"
    name = "Oceny"
    url = "teaching/oceny-zacniewski/"
    weight = 3

[[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 2

[[menu.main]]
    name = "About me"
    url = "pages/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
